const defaults={providerMode:'hybrid',providerEndpoint:'',providerKey:'',name:'Your Listener',wakePhrase:'your listener',aliases:[],style:'natural',avatar:'YL',avatarImage:'',snippet:{trigger:'',text:''}};
const settings={...defaults,...read('yourListenerSettings')};
const state={listening:false,starting:false,commandMode:false,recognition:null,activity:read('yourListenerActivity')||[]};
const $=id=>document.getElementById(id);
const el={name:$('name'),avatar:$('avatar'),avatarVisual:$('avatarVisual'),status:$('status'),heroTitle:$('heroTitle'),heroSubtitle:$('heroSubtitle'),micState:$('micState'),transcript:$('transcript'),command:$('command'),activity:$('activity')};
function read(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function apply(){el.name.textContent=settings.name;el.avatarVisual.textContent=settings.avatar||'YL';el.heroSubtitle.textContent=`Say “${settings.name}”, or hold Ctrl + Win + Alt to dictate anywhere.`;if(settings.avatarImage){el.avatarVisual.style.backgroundImage=`url(${settings.avatarImage})`;el.avatarVisual.style.backgroundSize='cover';el.avatarVisual.style.backgroundPosition='center';el.avatarVisual.style.color='transparent'}}
function setStatus(kind,text){el.status.className=`status ${kind||''}`;el.status.querySelector('span').textContent=text}
function render(){el.activity.innerHTML=state.activity.length?state.activity.map(x=>`<div class="item"><strong>${escape(x.command)}</strong><small>${escape(x.result)} · ${escape(x.time)}</small></div>`).join(''):'No activity yet.'}
function escape(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function log(command,result){state.activity.unshift({command,result,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});state.activity=state.activity.slice(0,20);localStorage.setItem('yourListenerActivity',JSON.stringify(state.activity));render()}
function wakeWords(){return [settings.wakePhrase,settings.name,...(settings.aliases||[])].map(norm).filter(Boolean)}
function stripWake(text){let n=norm(text);for(const word of wakeWords().sort((a,b)=>b.length-a.length)){if(n===word)return '';if(n.startsWith(word+' '))return n.slice(word.length+1)}return n}
function clean(text){let out=String(text||'').replace(/\b(um|uh|erm|hmm)\b[\s,]*/gi,'').replace(/\s+([,.!?])/g,'$1').replace(/\s{2,}/g,' ').trim();const s=settings.snippet||{};if(s.trigger&&s.text&&norm(out)===norm(s.trigger))out=s.text;if(settings.style==='concise')out=out.replace(/\b(very|really|just|basically)\b\s*/gi,'').replace(/\s{2,}/g,' ').trim();if(settings.style==='professional')out=out.replace(/\bgonna\b/gi,'going to').replace(/\bwanna\b/gi,'want to');return out}
function workflowAction(spoken){const rule=String(settings.workflow||'').match(/^\s*when\s+i\s+say\s+(.+?)\s*(?:→|->)\s*(.+)\s*$/i);if(!rule)return null;const trigger=norm(rule[1]);const heard=norm(spoken);return heard===trigger||heard.startsWith(trigger+' ')?rule[2].trim():null}
function setListening(on){state.listening=on;el.avatar.classList.toggle('listen',on);el.micState.textContent=on?'Microphone on':'Microphone off';if(on){setStatus('listen',state.commandMode?'Command mode — release keys to insert':`Listening for “${settings.wakePhrase}”`);el.heroTitle.textContent=state.commandMode?'Command mode':'I’m listening'}else{setStatus('','Ready when you are');el.heroTitle.textContent='Speak naturally'}}
async function insert(raw){const pressEnter=/\s*press enter\.?$/i.test(raw.trim());const base=clean(pressEnter?raw.replace(/\s*press enter\.?$/i,''):raw);const storedKey=await window.yourListener.secureGet({name:'providerKey'});const enhanced=await window.yourListener.enhanceText({mode:settings.providerMode||'hybrid',endpoint:settings.providerEndpoint||'',apiKey:storedKey?.value||'',text:base,style:settings.style||'natural'});const text=enhanced.text||base;const result=await window.yourListener.insertText(text,pressEnter);const msg=result.ok?(pressEnter?'Inserted enhanced text and pressed Enter.':'Inserted enhanced dictation into the focused app.'):result.error;el.transcript.textContent=msg;setStatus(result.ok?'':'error',msg);log(raw,msg)}
async function command(raw,requireWake=false){el.transcript.textContent=raw;const n=norm(raw);if(requireWake&&!wakeWords().some(w=>n===w||n.startsWith(w+' '))){setStatus('','Waiting for your calling name.');return}const c=stripWake(raw);if(!c){const msg='I heard my name. What should I do?';el.transcript.textContent=msg;log(raw,msg);return}if(/^(show )?help|what can you do/i.test(c)){const msg='I can dictate into the focused app, open websites, search the web, save notes, and run safe workflows.';el.transcript.textContent=msg;log(raw,msg);return}const note=c.match(/^(?:take a note|save a note|note)\s+(.+)/i);if(note){const notes=read('yourListenerNotes')||[];notes.unshift({text:note[1],at:new Date().toISOString()});localStorage.setItem('yourListenerNotes',JSON.stringify(notes.slice(0,100)));const msg=`Saved note: “${note[1]}”`;el.transcript.textContent=msg;log(raw,msg);return}const search=c.match(/^(?:search(?: for)?|look up)\s+(.+)/i);if(search){const r=await window.yourListener.openUrl('https://www.google.com/search?q='+encodeURIComponent(search[1]));const msg=r.ok?`Searching for “${search[1]}”.`:r.error;el.transcript.textContent=msg;log(raw,msg);return}const open=c.match(/^(?:open|visit|go to)\s+(.+)/i);if(open){const map={youtube:'https://youtube.com',google:'https://google.com',gmail:'https://mail.google.com',github:'https://github.com',spotify:'https://open.spotify.com'};const target=open[1].trim();const url=map[norm(target)]||(/^https?:\/\//i.test(target)?target:'https://'+target.replace(/\s+/g,''));const r=await window.yourListener.openUrl(url);const msg=r.ok?`Opening ${target}.`:r.error;el.transcript.textContent=msg;log(raw,msg);return}const connectors=read('yourListenerConnectors')||[];const routed=await window.yourListener.connectorRoute({text:c,connectors,permissions:{confirmed:false}});if(routed?.request?.intent?.kind&&routed.request.intent.kind!=='unknown'){const msg=routed.request.status==='needs_connector'?`I understood this as a ${routed.request.intent.kind} action, but no approved connector is configured yet.`:(routed.permission?.reason||routed.preview?.title||'Confirmation required.');el.transcript.textContent=msg;log(raw,msg);return}const workflow=workflowAction(c);if(workflow){log(raw,`Running safe workflow: ${workflow}`);await command(workflow,false);return}const refined=await window.yourListener.refinePrompt({input:c,context:{app:document.title,tone:settings.style||'clear and professional',format:'preserve meaning, remove filler, and apply useful punctuation'}});let msg='Improved prompt ready.';if(refined.questions&&refined.questions.length){msg='I need one detail before I can improve this: '+refined.questions.join(' ')}else if(refined.warnings&&refined.warnings.length){msg='Preview ready ('+refined.quality+'% quality). '+refined.warnings.join(' ')}el.transcript.textContent=msg;log(raw,msg)}
async function ensureMicrophone(){if(!navigator.mediaDevices?.getUserMedia)return{ok:false,error:'This Windows build does not expose the microphone API.'};try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.getTracks().forEach(track=>track.stop());return{ok:true}}catch(error){const messages={NotAllowedError:'Microphone permission is blocked. Enable microphone access for desktop apps in Windows Privacy settings.',NotFoundError:'No microphone was found. Connect a microphone and try again.',NotReadableError:'Windows could not read the microphone. Close other recording apps and try again.',SecurityError:'Microphone access was blocked by the app security policy.'};return{ok:false,error:messages[error.name]||`Microphone error: ${error.message||error.name}`}}}
function setupSpeech(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){el.micState.textContent='Speech engine unavailable — use typed test mode';setStatus('error','Speech recognition is unavailable in this build');return}const r=new R();r.continuous=true;r.interimResults=true;r.lang='en-US';r.onstart=()=>{state.starting=false;setListening(true);setStatus('listen',state.commandMode?'Command mode — speak now':`Listening for “${settings.wakePhrase}”`)};r.onaudiostart=()=>{el.micState.textContent='Microphone signal detected'};r.onend=()=>{if(state.listening&&!state.commandMode)setTimeout(()=>{try{r.start()}catch{}},250)};r.onerror=e=>{state.starting=false;const messages={'not-allowed':'Microphone permission is blocked in Windows Privacy settings.','audio-capture':'No microphone signal was received.','service-not-allowed':'The Windows speech service denied access.','network':'Speech service connection failed.'};if(messages[e.error]){setListening(false);setStatus('error',messages[e.error]);el.transcript.textContent=messages[e.error]}};r.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?finalText+=t:interim+=t}if(interim)el.transcript.textContent=interim;if(finalText.trim())state.commandMode?insert(finalText.trim()):command(finalText.trim(),true)};state.recognition=r}
async function start(){if(state.starting||state.listening)return;if(!state.recognition){el.transcript.textContent='Speech recognition is unavailable. Use the test console.';return}state.starting=true;setStatus('listen','Requesting microphone permission…');const mic=await ensureMicrophone();if(!mic.ok){state.starting=false;el.transcript.textContent=mic.error;setStatus('error',mic.error);return}try{state.recognition.start()}catch(error){state.starting=false;setStatus('error',`Could not start speech recognition: ${error.message}`)}}function stop(){state.starting=false;try{state.recognition?.stop()}catch{}setListening(false)}
el.avatar.addEventListener('click',()=>state.listening?stop():start());$('run').addEventListener('click',()=>{if(el.command.value.trim()){command(el.command.value.trim());el.command.value=''}});el.command.addEventListener('keydown',e=>{if(e.key==='Enter')$('run').click()});document.querySelectorAll('.quick button').forEach(b=>b.addEventListener('click',()=>command(b.dataset.command)));$('settings').onclick=()=>window.yourListener.openSettings();$('minimize').onclick=()=>window.yourListener.minimizeWindow();$('close').onclick=()=>window.yourListener.closeWindow();$('clear').onclick=()=>{state.activity=[];localStorage.removeItem('yourListenerActivity');render()};window.addEventListener('storage',e=>{if(e.key==='yourListenerSettings'){Object.assign(settings,read(e.key)||defaults);apply()}});window.yourListener.onCommandModeStart(()=>{state.commandMode=true;start()});window.yourListener.onCommandModeStop(()=>{stop();setTimeout(()=>state.commandMode=false,300)});apply();render();setupSpeech();setTimeout(()=>{if(state.recognition)start()},700);
